name = "exchange-api-hono"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun install && bun run build"

[build.upload]
format = "modules"

main = "./dist/index.js"